name: schulplaner_addons
description: Simply the flutter workflow:)
version: 0.1.0
publish_to: none

environment:
  sdk: ">2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  bloc:
    path: ../bloc
  #GENERAL
  uuid: ^3.0.5
  #FILES AND IMAGES
  cached_network_image: 3.2.0
  path_provider: ^2.0.8
  image: 3.1.1
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.4+5
  file_picker: ^4.3.3
  photo_view: ^0.13.0
  #FIREBASE
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  #MORE
  url_launcher: 6.0.18
  universal_io: ^2.0.4
  overlay_support: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1
  plugin_platform_interface: ^2.1.2
  petitparser: ^4.4.0
  xml: ^5.0.2
  crypto: ^3.0.1
  


flutter: