name: schulplaner_addons
description: Simply the flutter workflow:)
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  bloc:
    path: ../bloc
  #GENERAL
  uuid: ^4.2.1
  #FILES AND IMAGES
  cached_network_image: 3.3.0
  path_provider: ^2.1.1
  image: 4.1.3
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.1.0
  image_picker: 1.0.4
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  #FIREBASE
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.13.1
  #MORE
  url_launcher: 6.2.1
  universal_io: ^2.2.2
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  


flutter: