name: schulplaner_functions
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  app_functions:
    path: ../app_functions
  schulplaner_models:
    path: ../schulplaner_models
  bloc:
    path: ../bloc
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  intl: ^0.17.0
  petitparser: ^4.4.0
  xml: ^5.0.2
  crypto: ^3.0.1
  intl_translation:
    git:
      url: https://github.com/Zazo032/intl_translation.git
      ref: patch-1

flutter:
