name: schulplaner_navigation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  rxdart: ^0.27.7
  shared_preferences: 2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
