name: schulplaner8
description: An all-in-one open-source school-planner app for Android, iOS, ChromeOS and the web!
publish_to: none
version: 10.0.1+611

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  schulplaner_addons:
    path: ../packages/schulplaner_addons
  schulplaner_widgets:
    path: ../packages/schulplaner_widgets
  bloc:
    path: ../packages/bloc
  authentification:
    path: ../packages/authentification
  universal_commons:
    path: ../packages/universal_commons
  schulplaner_translations:
    path: ../packages/schulplaner_translations
  date:
    path: ../packages/date
  app_functions:
    path: ../packages/app_functions
  schulplaner_functions:
    path: ../packages/schulplaner_functions
  schulplaner_models:
    path: ../packages/schulplaner_models
  schulplaner_navigation:
    path: ../packages/schulplaner_navigation
  schulplaner_website:
    path: ../schulplaner_website
  export_user_data_client:
    path: ../packages/export_user_data/export_user_data_client
  export_user_data_client_implementation:
    path: ../packages/export_user_data/export_user_data_client_implementation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 2.2.2
  cupertino_icons: 1.0.6

  #GOOGLE
  firebase_core: ^2.22.0
  cloud_firestore: 4.13.1
  firebase_auth: 4.14.0
  firebase_messaging: 14.7.4
  firebase_storage: 11.5.1
  firebase_analytics: 10.7.0
  firebase_database: 10.3.4
  firebase_performance: 0.9.3+4
  firebase_crashlytics: 3.4.4
  firebase_dynamic_links: 5.4.4
  firebase_remote_config: ^4.3.4

  intl: ^0.18.1
  intl_translation: 0.18.2
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0
  
  community_material_icon: 5.9.55
  font_awesome_flutter: ^10.6.0
  color: 3.0.0
  flutter_colorpicker: 1.0.3
  string_similarity: ^2.0.0
  qr_flutter: 4.1.0
  device_info_plus: 9.1.0
  url_launcher: 6.2.1
  decimal: 2.3.3
  share: 2.0.4
  tuple: 2.0.2
  launch_review: 3.0.1
  flutter_image_compress: 2.1.0
  photo_view: 0.14.0
  path_provider: 2.1.1
  cached_network_image: 3.3.0
  flutter_cache_manager: 3.3.1
  auto_size_text: 3.0.0
  filesize_ns: ^1.1.0
  image: 4.1.3
  dots_indicator: ^2.1.2
  timeago: ^3.2.2
  fl_chart: ^0.45.1
  percent_indicator: ^4.2.3
  printing: ^5.11.1
  pdf: ^3.10.6
  overlay_support: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/about_me_felix.jpg