name: authentification
description:  Authentifizierung für die Schulplaner App
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  schulplaner_widgets:
    path: ../schulplaner_widgets
  schulplaner_translations:
    path: ../schulplaner_translations
  universal_commons:
    path: ../universal_commons
  firebase_auth: 4.14.0
  google_sign_in: 6.1.6
  sign_in_with_apple: ^5.0.0
  rxdart: ^0.27.7
  community_material_icon: 5.9.55
  url_launcher: any
  googleapis_auth: 1.4.1
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

