name: date
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
