name: universal_commons
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
