include: package:flutter_lints/flutter.yaml


analyzer:
    errors:
      invalid_use_of_protected_member: ignore
      invalid_use_of_visible_for_testing_member: ignore
      import_of_legacy_library_into_null_safe: ignore

linter:
  rules: 
    omit_local_variable_types: false
    prefer_conditional_assignment: false
    prefer_generic_function_type_aliases: false
    prefer_if_null_operators: false

#   exclude:
#     - path/to/excluded/files/**