name: schulplaner_website
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">2.12.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../packages/bloc
  design_utils:
    path: ../packages/design_utils
  cupertino_icons: ^1.0.4
  url_launcher: 6.2.1
  flutter_svg: ^1.1.6
  community_material_icon: ^5.9.55
  carousel_slider: ^4.2.1
  easy_dynamic_theme: ^2.3.1
  #url_strategy: 0.2.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/badges/
    - assets/screenshots/
    - assets/privacy_policy_schulplaner.pdf
