name: schulplaner_widgets
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.16.0"

dependencies:
  color: 3.0.0
  schulplaner_translations:
    path: ../schulplaner_translations
  app_functions:
    path: ../app_functions
  universal_commons:
    path: ../universal_commons
  rxdart: ^0.27.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

