name: schulplaner_widgets
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">2.12.0"
  flutter: ">2.0.0"

dependencies:
  color: 3.0.0
  schulplaner_translations:
    path: ../schulplaner_translations
  app_functions:
    path: ../app_functions
  universal_commons:
    path: ../universal_commons
  rxdart: ^0.27.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

