name: schulplaner_models
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  authentification:
    path: ../authentification
  schulplaner_addons:
    path: ../schulplaner_addons
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: